---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(tidyr)
```
#read the data
```{r}
# Data of Wave 5


WV5_data <- readRDS("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/F00007944-WV5_Data_R_v20180912.rds")


# Convert WV5_data-object in data.frame 
WV5_data_df <- as.data.frame(WV5_data)

# show first five columns
head(WV5_data_df[, 1:5])
```

``
```{r}
library(dplyr)

#rename the variables
WV5_data <- WV5_data_df %>%
  rename(risk_and_adventure = V86, sex = V235, age = V237, country = V2)
WV5_data


#select only the variables of interest
WV5_data <- WV5_data %>%
  select(risk_and_adventure, sex, age, country)
WV5_data
```

```{r}
#exlcusion of participants with no info about risk, sex, age, employment, merital status and children 
WV5_data_df = subset(WV5_data, risk_and_adventure > 0 & sex > 0 & age >0)
```

```{r}
#decode the country names 
countrynames = read.csv("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/countrynames.txt", header=FALSE,as.is=TRUE)
colnames(countrynames) = c("code", "name")
WV5_data$country_lab = countrynames$name [match(WV5_data$country, countrynames$code)]
table(WV5_data$country_lab)
WV5_data


```


```{r}

library(ggplot2)

p = ggplot(WV5_data_df, aes(as.factor(sex),risk_and_adventure))+
  geom_boxplot()+
  theme_bw()
p


```


```{r}

p2 <- ggplot(WV5_data, aes(x = risk_and_adventure, y = sex, color = as.factor(country_lab))) +
  geom_point() +
  geom_smooth(method = "lm", se = TRUE)
p2


```
```{r}
WV6_data <- load("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/WV6_Data_R_v20201117.rdata") 
WV6_data <- WV6_Data_R_v20201117 
print(WV6_data)
```
```{r}
WV6_data <- WV6_data %>%
  rename(risk_and_adventure = V76, sex = V240, age = V242, education = V237, country = V2)


#select only the variables of interest
WV6_data <- WV6_data %>%
  select(risk_and_adventure, sex, age, country)
WV6_data

```
```{r}
countrynames = read.csv("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/countrynames.txt", header=FALSE,as.is=TRUE)
colnames(countrynames) = c("code", "name")
WV6_data$country_lab = countrynames$name [match(WV6_data$country, countrynames$code)]
table(WV6_data$country_lab)
WV6_data
```
```{r}
WV6_data = subset(WV6_data, risk_and_adventure > 0 & sex > 0 & age >0)
data = rbind(WV5_data, WV6_data)
data
```


