---
title: "R Notebook"
output: html_notebook
---
Variables: 

Risk
Age 
Sex
Country


```{r}
library(data.table)
library(tidyr)
library(maps)
library(haven)
library(ggplot2)
library(dplyr)

```

#read the data (Wave 5)
```{r}
# Data of Wave 5


WV5_data <- readRDS("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/F00007944-WV5_Data_R_v20180912.rds")


# Convert WV5_data-object in data.frame 
WV5_data_df <- as.data.frame(WV5_data)

# show first five columns
WV5_data_df
```

# clean the data set
```{r}
library(dplyr)

#rename the variables
WV5_data <- WV5_data_df %>%
  rename(gender = V235, age = V237, country_code = V2, wave = V1, risktaking = V86)
WV5_data


#select only the variables of interest
WV5_data <- WV5_data %>%
  select(gender, age, country_code, wave, risktaking)
WV5_data
```

```{r}
#decode the country names 
#countrynames = read.csv("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/countrynames.txt", header=FALSE,as.is=TRUE)
colnames(countrynames) = c("code", "name")
WV5_data$country = countrynames$name [match(WV5_data$country_code, countrynames$code)]
table(WV5_data$country)
WV5_data



#Read Dataset (Wave 6)

WV6_data <- load("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/WV6_Data_R_v20201117.rdata") 
WV6_data <- WV6_Data_R_v20201117 
print(WV6_data)
```

#rename variables
```{r}
WV6_data <- WV6_data %>%
  rename(wave = V1, gender = V240, age = V242,country_code = V2, risktaking = V76 )


#select only the variables of interest
WV6_data <- WV6_data %>%
  select(wave, gender, age, country_code,risktaking)
WV6_data

```


#decode daraset (Wave 6)
```{r}
countrynames = read.csv("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/countrynames.txt", header=FALSE,as.is=TRUE)
colnames(countrynames) = c("code", "name")
WV6_data$country = countrynames$name [match(WV6_data$country_code, countrynames$code)]
table(WV6_data$country)
WV6_data
```

#combine the 2 dataset (Wave 6 + Wave 5)
```{r}
WV5_data
WV6_data
WVS_data = rbind(WV5_data, WV6_data)
WVS_data





```
#exclusion of participants and omission of missing data (na)
```{r}
WVS_data = subset(WVS_data, risktaking > 0 & gender > 0 & age >0 )
data_Wave5 = subset(WV5_data, risktaking > 0 & gender > 0 & age >0 )
data_Wave6 = subset(WV6_data, risktaking > 0 & gender > 0 & age >0)
WVS_data <- na.omit(WVS_data)
data_Wave5 <- na.omit(data_Wave5)
data_Wave6 <- na.omit(data_Wave6)


# Use the mutate function to change the country name
WVS_data <- WVS_data %>%
  mutate(country = ifelse(country == "Great Britain", "United Kingdom", country))
```
```{r}
# Transfrom risk item such that high values represent more risk taking
WVS_data$risktaking = 6 - WVS_data$risktaking + 1

  
# Transform risk variable into T-score (mean = 50, sd = 10)
WVS_data$T_score_risktaking = 10*scale(WVS_data$risktaking, center=TRUE,scale=TRUE)+50

WVS_data

#Transform risk variable into Z score 

# Assuming T-scores have a mean of 50 and a standard deviation of 10
WVS_data$Z_score_risktaking = (WVS_data$T_score_risktaking - 50) / 10

# Print the resulting data frame
print(WVS_data)

WVS_data <- WVS_data %>%
  group_by(country) %>%
  mutate(z_score_age = scale(age))
WVS_data






```
#World map 
```{r}
world_map <- map_data("world")
recorded_countries <- unique(WVS_data$country)
world_map$recorded <- ifelse(world_map$region %in% recorded_countries, "Recorded", "Not Recorded")

ggplot(world_map, aes(x = long, y = lat, group = group, fill = recorded)) + 
  geom_polygon(color = "white") +
  scale_fill_manual(values = c("Recorded" = "red", "Not Recorded" = "lightgrey"), guide = "none") +
  theme_void() +
  labs(title = "WVS", fill = "Status") +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5))

```

```{r}
# Load the dplyr package
library(dplyr)

# Assuming the data frame is called 'data' and the column containing the country information is called 'country'
country_counts <- WVS_data %>%
  count(country)

# Print the result
print(country_counts)

```

```{r}
# read in file that contains hardship indicators manually collected from CIA factbook, WHO, and World Bank 
# (see Supplemental Materials for URL sources)
countryfacts = read.csv("/Users/cristinacandido/Documents/Github/risk_wvs/data/WVS/countryfacts_selection.csv", as.is = TRUE, header = TRUE) 

# Create a vector of labels with the same length as the number of columns in 'countryfacts'
labels <- c("code","country","codeWVS","Homicide","GDP","InfMort","LifeExp","GINI","GenderPEdu","code2")




# Print the result
print(countryfacts)
```
```{r}
# Load the dplyr package if not already loaded
if (!require(dplyr)) {
  install.packages("dplyr")
  library(dplyr)
}

# Create the 'hardship' column in the 'countryfacts' data frame
countryfacts <- countryfacts %>%
  mutate(hardship = (homiciderate + gdp + infantmortality + lifeexpectancy + gini + femalemale_primedu) / 6)
countryfacts



# View the distribution of the 'hardship_index' column for each country
hardship_index_distribution <- countryfacts %>%
  group_by(label) %>%
  summarize(
    mean = mean(hardship, na.rm = TRUE),
    median = median(hardship, na.rm = TRUE),
    sd = sd(hardship, na.rm = TRUE),
    min = min(hardship, na.rm = TRUE),
    max = max(hardship, na.rm = TRUE),
    n = sum(!is.na(hardship))
  )

# Print the result
print(hardship_index_distribution)
```

#table with female percentage, mean age, mean risk taking per countries (summary of the countries)
```{r}
library(dplyr)

table_data_WVS <- WVS_data %>%
  group_by(country) %>%
  summarise(
    n = n(),
    female_percentage = mean(gender == 1) * 100,
    mean_age = mean(age, na.rm = TRUE),
    age_range = paste(min(age, na.rm = TRUE), "-", max(age, na.rm = TRUE)),
    mean_risktaking = mean(Z_score_risktaking, na.rm = TRUE)
  )

table_data_WVS
```
```{r}
#graph across countries: risk taking vs age vs gender (Z-score for age and risk taking)   


# Risk vs age with color-coded gender per Country
# Risk vs age with color-coded gender per Country
# Skalierung des Z-Scores für das Alter anpassen
WVS_data$z_score_age_scaled <- 15 * WVS_data$z_score_age + 42


ggplot(WVS_data, aes(z_score_age_scaled, Z_score_risktaking, color = as.factor(gender))) +
  geom_point(position = position_jitter(width = 0.1, height = 0.1), size = 0.1) +  
  geom_smooth(method = "lm") +
  geom_vline(xintercept = 42, linetype = "dashed", color = "black", size = 1) +  
  scale_color_manual(values = c("blue", "red"), labels = c("Male", "Female")) +
  labs(color = "Gender") +
  xlab("Age") +
  ylab("Risk Taking") +
  scale_x_continuous(breaks = seq(0, 100, by = 15), limits = c(0, 100)) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))



WVS_data









```


```{r}
#regression table (risk taking and age -> Z-score)

regression_results_WVS <- WVS_data %>%
  group_by(country) %>%
  do(model = lm(Z_score_risktaking ~ scale(age) + gender, data = .)) %>%
  summarize(
    country = first(country),
    intercept = coef(summary(model))[1, 1],
    slope_age = coef(summary(model))[2, 1],
    slope_gender = coef(summary(model))[3, 1]
  )

regression_results_WVS


```


```{r}
gps_data <- haven::read_dta("/Users/cristinacandido/Documents/Github/risk_wvs/data/individual_new.dta")

gps_data
```
```{r}
# Clean the data by removing records with missing values
gps_data <- gps_data %>%
  drop_na(country, isocode, risktaking, gender, age)



# Display the cleaned data
gps_data
```
```{r}
#select only the variables of interest
gps_data <- gps_data %>%
  select(country, isocode, ison, risktaking, gender, age)
gps_data
```
```{r}
#Z-score for age 
gps_data <- gps_data %>%
  group_by(country) %>%
  mutate(z_score_age = scale(age))

# Display the new column with Z-Scores per Country
gps_data
```
#table intercept and slope 
```{r}
regression_results_gps <- gps_data %>%
  group_by(country) %>%
  do(model = lm(risktaking ~ z_score_age + gender, data = .)) %>%
  summarize(
    country = first(country),
    intercept = coef(summary(model))[1, 1],
    slope_age = coef(summary(model))[2, 1],
    slope_gender = coef(summary(model))[3, 1]
  )

regression_results_gps
```
```{r}
common_countries <- intersect(WVS_data$country, gps_data$country)
selected_countries <- c("Argentina", "Australia", "Brazil", "Canada", "Chile", "China", "Egypt", "Finland", "France", "Georgia",
                         "Germany", "Ghana", "Hungary", "India", "Indonesia", "Iran", "Japan", "Jordan", "Mexico", "Moldova",
                         "Morocco", "Netherlands", "Peru", "Poland", "Romania", "Russia", "Rwanda", "South Africa", "South Korea",
                         "Spain", "Sweden", "Switzerland", "Thailand", "Turkey", "Ukraine", "United States", "Algeria", "Colombia",
                         "Estonia", "Haiti", "Iraq", "Kazakhstan", "Nigeria", "Pakistan", "Philippines", "Zimbabwe", "United Kingdom")

# Filter the original dataset
new_WVS <- WVS_data[WVS_data$country %in% selected_countries, ]

# View the new dataset
new_WVS


```

```{r}

selected_countries <- c("Argentina", "Australia", "Brazil", "Canada", "Chile", "China", "Egypt", "Finland", "France", "Georgia",
                         "Germany", "Ghana", "Hungary", "India", "Indonesia", "Iran", "Japan", "Jordan", "Mexico", "Moldova",
                         "Morocco", "Netherlands", "Peru", "Poland", "Romania", "Russia", "Rwanda", "South Africa", "South Korea",
                         "Spain", "Sweden", "Switzerland", "Thailand", "Turkey", "Ukraine", "United States", "Algeria", "Colombia",
                         "Estonia", "Haiti", "Iraq", "Kazakhstan", "Nigeria", "Pakistan", "Philippines", "Zimbabwe", "United Kingdom")

# Filter the original dataset
new_gps <- gps_data[gps_data$country %in% selected_countries, ]

# View the new dataset
new_gps

```
```{r}
regression_results_WVS_new <- new_WVS %>%
  group_by(country) %>%
  do(model = lm(Z_score_risktaking ~ scale(age) + gender, data = .)) %>%
  summarize(
    country = first(country),
    intercept_WVS = coef(summary(model))[1, 1],
    slope_age_WVS = coef(summary(model))[2, 1],
    slope_gender_WVS = coef(summary(model))[3, 1]
  )

regression_results_WVS_new

```
```{r}
regression_results_gps_new <- new_gps %>%
  group_by(country) %>%
  do(model = lm(risktaking ~ scale(age) + gender, data = .)) %>%
  summarize(
    country = first(country),
    intercept_gps = coef(summary(model))[1, 1],
    slope_age_gps = coef(summary(model))[2, 1],
    slope_gender_gps = coef(summary(model))[3, 1]
  )

regression_results_gps_new

```
```{r}
regression_results_gps_new
regression_results_WVS_new
# Assuming "country" is the common column
merged_results <- merge(regression_results_gps_new, regression_results_WVS_new, by = "country", all = TRUE)

merged_results

new_data <- read_excel("/Users/cristinacandido/Documents/Github/risk_wvs/data/Hardship.xlsx") # Read data from the Excel file

labels <- c("code")

print(new_data)

new_data <- left_join(merged_results, new_data, by = "country") # Perform the left_join operation
new_data

new_data <- new_data %>%
  select(country, intercept_gps, slope_age_gps, slope_gender_gps, intercept_WVS, slope_age_WVS, slope_gender_WVS, isocode )
new_data



```
```{r}
# Plotting comparing interecepts
ggplot(new_data, aes(x = intercept_gps, y = intercept_WVS, label = isocode)) +
  geom_point(size = 1.5) +
  geom_text(aes(label = isocode), vjust = -0.5, hjust = -0.5) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  labs(title = "Comparison of Intercept Values",
       x = "Intercept_gps",
       y = "Intercept_WVS") +
  theme_minimal() +
  xlim(c(0, 1.2)) +
  ylim(c(0, 1.2)) +
  coord_fixed()

# Assuming you have a data frame named 'new_data' with columns 'intercept_gps', 'intercept_WVS', and 'isocode'

# Install and load the necessary packages
library(ggplot2)
library(ggrepel)
library(wordcloud)

# Assuming you have a data frame named 'new_data' with columns 'intercept_gps', 'intercept_WVS', and 'isocode'

# Scatter plot with labels
library(ggplot2)
library(ggrepel)

# Assuming you have a data frame named 'new_data' with columns 'intercept_gps', 'intercept_WVS', and 'isocode'

ggplot(new_data, aes(x = intercept_gps, y = intercept_WVS, label = isocode)) +
  geom_point(size = 3) +
  geom_text_repel(
    aes(label = isocode),
    box.padding = 0.5,
    point.padding = 0.1,
    force = 5
  ) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  labs(x = "Intercept Global Preference Study",
       y = "Intercept World Value Survey") +
  theme_minimal() +
  xlim(c(0, 1.07)) +
  ylim(c(0, 1.07)) +
  coord_fixed()


# Annotate with word cloud
wordcloud(words = new_data$isocode, freq = rep(1, nrow(new_data)), scale = c(2, 0.5))


# Annotate with word cloud
wordcloud(words = new_data$isocode, freq = rep(1, nrow(new_data)), scale = c(2, 0.5))




# Assuming merged_results has columns intercept_gps and intercept_WVS
model <- lm(intercept_WVS ~ intercept_gps, data = merged_results)

# View the summary of the regression model
summary(model)

# Calculate the correlation
correlation <- cor(merged_results$intercept_gps, merged_results$intercept_WVS)

# Print the correlation coefficient
print(correlation)



  

```

```{r}
library(ggplot2)



# Plotting using ggplot2
ggplot(new_data, aes(x = slope_age_gps, y = slope_age_WVS, label = isocode)) +
  geom_point(size = 3) +
  geom_text_repel(
    aes(label = isocode),
    box.padding = 0.5,
    point.padding = 0.1,
    force = 5
  ) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  labs(x = "Effect of Age on Risk Taking Global Preference Study",
       y = "Effect of Age on Risk Taking World Value Survey") +
  theme_minimal() +
  xlim(-0.5, 0) +
  ylim(c(-0.5, 0)) +
  coord_fixed()

new_data

correlation <- cor(new_data$slope_age_gps, new_data$slope_age_WVS)

# Print the correlation coefficient
print(correlation)

```


```{r}
# Plotting using ggplot2
ggplot(new_data, aes(x = slope_gender_gps, y = slope_gender_WVS, label = isocode)) +
  geom_point(size = 3) +
  geom_text_repel(
    aes(label = isocode),
    box.padding = 0.5,
    point.padding = 0.1,
    force = 5
  ) +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed") +
  labs(x = "Effect of Gender on Risk Taking Global Preference Study",
       y = "Effect of Gender on Risk Taking World Value Survey") +
  theme_minimal() +
  xlim(-0.6, 0.12) +
  ylim(c(-0.6, 0.12)) +
  coord_fixed()

new_data

correlation <- cor(new_data$slope_gender_gps, new_data$slope_gender_WVS)

# Print the correlation coefficient
print(correlation)
```
#Hardship for gps data
```{r}
library(readxl)
hardship_values <- read_excel("/Users/cristinacandido/Documents/Github/risk_wvs/data/Hardship.xlsx") # Read data from the Excel file

print(colnames(gps_data)) # Display column names in cleaned_data

print(colnames(hardship_values)) # Display column names in hardship_data

hardshipgps <- left_join(gps_data, hardship_values, by = "country") # Perform the left_join operation

hardshipgps

```
```{r}
completegps <- hardshipgps %>%
  group_by(country) %>%
  summarise(
    n = n(),
    female_percentage = mean(gender == 1) * 100,
    mean_age = mean(z_score_age, na.rm = TRUE),
    mean_risktaking = mean(risktaking, na.rm = TRUE),
    mean_hardshipindex = mean(hardship, na.rm = TRUE)
  )

  completeWVS
  

```

```{r}
#hardship for WVS
library(readxl)
hardship_values <- read_excel("/Users/cristinacandido/Documents/Github/risk_wvs/data/Hardship.xlsx") # Read data from the Excel file

labels <- c("country", "code", "gdp", "gini", "Infant_mortality", "life_expect", "hardship")

print(hardship_values)

hardshipWVS <- left_join(WVS_data, hardship_values, by = "country") # Perform the left_join operation
hardshipWVS



```
```{r}
# Assuming your dataset is named WVS_data
# Assuming your dataset is named WVS_data
WVS_data$Z_score_age <- scale(WVS_data$age, center = mean(WVS_data$age, na.rm = TRUE), scale = sd(WVS_data$age, na.rm = TRUE))

WVS_data


completeWVS <- hardshipWVS %>%
  group_by(isocode,country) %>%
  summarise(
    n = n(),
    female_percentage = mean(gender == 1) * 100,
    mean_age = mean(age, na.rm = TRUE),
    mean_risktaking = mean(risktaking, na.rm = TRUE),
    mean_hardshipindex = mean(hardship, na.rm = TRUE)
  )


  completeWVS
```
```{r}
completegps
completeWVS
```

```{r}
hardshipWVS
```















